# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac23bd97f5ef185f090dd56e86569ee591c373c2dbcdcd8172ce8b41c30f32669beca459f8776545dcac51624e2a026b767c3503e081f10d4c680895e2e12082

test:
  secret_key_base: 373676eddb39f3fcc91e008ea59608f4d427de25752ca6d8639a65b17e45da95d3ce72e1be1904a35340b67c23f3159dcc613bdb7822588b5f6874a4e5c54c4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
